# Generated by Django 6.0.1 on 2026-01-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('kategori', models.CharField(choices=[('Pria', 'Fashion Pria'), ('Wanita', 'Fashion Wanita'), ('Anak', 'Fashion Anak-anak')], max_length=10)),
                ('harga', models.IntegerField()),
                ('deskripsi', models.TextField()),
                ('gambar_url', models.URLField(help_text='Masukkan URL gambar saja agar praktis')),
            ],
        ),
    ]
