# Generated by Django 6.0.1 on 2026-01-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='punya_ukuran',
            field=models.BooleanField(default=True, help_text='Ceklis jika produk ini butuh pilihan S, M, L, XL'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_url',
            field=models.URLField(),
        ),
    ]
