# Generated by Django 6.0.1 on 2026-01-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0002_produk_punya_ukuran_alter_produk_gambar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='punya_ukuran_sepatu',
            field=models.BooleanField(default=True, help_text='Ceklis jika produk ini butuh pilihan angka (37, 38, 39, dst)', verbose_name='Punya ukuran sepatu'),
        ),
    ]
