# Generated by Django 6.0.1 on 2026-01-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0003_produk_punya_ukuran_sepatu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='punya_ukuran',
            field=models.BooleanField(default=False, help_text='Ceklis jika produk ini butuh pilihan S, M, L, XL'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='punya_ukuran_sepatu',
            field=models.BooleanField(default=False, help_text='Ceklis jika produk ini butuh pilihan angka sepatu'),
        ),
    ]
